{% set name = "meshplot" %}
{% set version = "v0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/skoch9/meshplot/archive/{{ version }}.tar.gz
  sha256: c527a14d803044b190d6da4a21c8507da1bd8d7dc3d449f771da1f5cf00e6ac9

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
  host:
    - python
    - pip
  run:
    - python
    - pythreejs
    - numpy
    - matplotlib
    - ipywidgets

test:
  imports:
    - meshplot

about:
  home: https://github.com/skoch9/meshplot
  license: GPL-3.0
  license_family: GPL
  summary: 'Simple, fast, plotting of 3D triangle meshes'

  description: 'Simple, fast, plotting of 3D triangle meshes'
  doc_url: https://github.com/skoch9/meshplot
  dev_url: https://github.com/skoch9/meshplot

extra:
  recipe-maintainers:
    - skoch9
    - teseoch
