{% set name = "meshplot" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: v{{ version }}

source:
  url: https://github.com/skoch9/meshplot/archive/v{{ version }}.tar.gz
  sha256: a550cfdb814913b793bd2407249aef2da690ea0ced8705da2a8feb3c421ebd9b

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
  host:
    - python
    - pip
  run:
    - python
    - pythreejs
    - numpy
    - matplotlib
    - ipywidgets

test:
  imports:
    - meshplot

about:
  home: https://github.com/skoch9/meshplot
  license: GPL-3.0
  license_file: LICENSE
  license_family: GPL
  summary: 'Simple, fast, plotting of 3D triangle meshes'

  description: 'Simple, fast, plotting of 3D triangle meshes'
  doc_url: https://github.com/skoch9/meshplot
  dev_url: https://github.com/skoch9/meshplot

extra:
  recipe-maintainers:
    - skoch9
    - teseoch
