{% set name = "meshplot" %}
{% set version = "v0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/skoch9/meshplot/archive/{{ version }}.tar.gz
  sha256: f73344b7e474d2115671dd09c2f026d59ca42ca5c5c76c003d6c13bf20ea0dd0

build:
  noarch: python
  number: 3
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
  host:
    - python
    - pip
  run:
    - python
    - pythreejs
    - numpy
    - matplotlib
    - ipywidgets

test:
  imports:
    - meshplot

about:
  home: https://github.com/skoch9/meshplot
  license: GPL-3.0
  license_family: GPL
  summary: 'Simple, fast, plotting of 3D triangle meshes'

  description: 'Simple, fast, plotting of 3D triangle meshes'
  doc_url: https://github.com/skoch9/meshplot
  dev_url: https://github.com/skoch9/meshplot

extra:
  recipe-maintainers:
    - skoch9
    - teseoch
