travis:
  secure:
    BINSTAR_TOKEN: utFNz6f80tERtph7ckEQemFagu7bCTykhwF2SCsk9aU8+8m6u7i2AqIUk4h2iqFv+DWold6toheCG7XbChEpbaeTyK1aPUEdVqRS98PBv589EucdtVarMiSms7m6i/Tzlqwollo/HXOSnnQqjvBhHS7loxIvBqsG7mYAH2tD4EhMgZ3KOldXcLRkMChOLSLvqO0DQk2BybicXidgHVBBsF0jovsTxGEVJ2+TD+9LTUrLLwUCzpN69i+M4c2icxbUATd1AsaagUhYaF0LSR31npnjOBkyeBjdWOh2A4eLkdLoesHgblziASJtYWP8ex9Go2nwlb1YmPSiLV+KeTYkpDd/2c6jntILIeZyIx/I4kMkt9TEol8hisS3SWE8Yz2ICfTA2KXGN6fulvXIInQ97h+VU+t4nttMeLuWQI0XlMxgCyzeTZb/7eBK9pFqf2hjpPhOlBo4ajoqa3iTPMENLhiqV3ZC1E0Ee4pasDcYxETTniKP9jiFrJigHimO1pSojhOOeS+Y6BlwrqyRhN6fNiuqcM20oFpD/1aq5b7Xdsw4JfOUjdR3bmQB+WvDzegDfsq38gzvy3+cpjZ+GPak4R8vZb2uvORrRs5hoDidJtZaDhg/xapXvgieHXvYIpENdpgUuAr421bl+OXVwQn7fT1+tD5SAMMMLJWyuHQrnqw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
